<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage1.master" AutoEventWireup="true" CodeFile="ShowData.aspx.cs" Inherits="Default6" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <style type="text/css">
        .style9
        {
            width: 100%;
            background-color: #FFFF99;
        }
    </style>
    </asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <table class="style9">
        <tr>
            <td colspan="2" 
                style="text-align: center; font-weight: 700; font-style: italic">
                Category Information</td>
        </tr>
        <tr>
            <td>
                &nbsp;</td>
            <td>
                &nbsp;</td>
        </tr>
        <tr>
            <td colspan="2">
                <asp:GridView ID="GridView1" runat="server" AllowPaging="True" 
                    AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
                    AutoGenerateEditButton="True" BackColor="White" 
                    BackImageUrl="~/Images/four-red-and-yellow-fishs-in-the-water-with-white-background-hd-wallpapers-1600-x-1200.jpg" 
                    BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" CellPadding="4" 
                    DataKeyNames="Category_ID" DataSourceID="SqlDataSource3" ForeColor="Black" 
                    GridLines="None" PageSize="5" style="text-align: center" Width="924px">
                    <Columns>
                        <asp:BoundField DataField="Category_ID" HeaderText="Category_ID" 
                            InsertVisible="False" ReadOnly="True" SortExpression="Category_ID" />
                        <asp:BoundField DataField="Category_Name" HeaderText="Category_Name" 
                            SortExpression="Category_Name" />
                    </Columns>
                    <FooterStyle BackColor="#CCCC99" ForeColor="Black" />
                    <HeaderStyle BackColor="#333333" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="White" ForeColor="Black" HorizontalAlign="Right" />
                    <SelectedRowStyle BackColor="#CC3333" Font-Bold="True" ForeColor="White" />
                    <SortedAscendingCellStyle BackColor="#F7F7F7" />
                    <SortedAscendingHeaderStyle BackColor="#4B4B4B" />
                    <SortedDescendingCellStyle BackColor="#E5E5E5" />
                    <SortedDescendingHeaderStyle BackColor="#242121" />
                </asp:GridView>
                <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
                    ConnectionString="<%$ ConnectionStrings:ConnectionString %>" 
                    SelectCommand="SELECT * FROM [Brand_Table]"></asp:SqlDataSource>
            </td>
        </tr>
        <tr>
            <td colspan="2" 
                style="text-align: center; font-weight: 700; font-style: italic">
                Brand Information</td>
        </tr>
        <tr>
            <td>
                &nbsp;</td>
            <td>
                &nbsp;</td>
        </tr>
        <tr>
            <td colspan="2">
                <asp:GridView ID="GridView2" runat="server" AllowPaging="True" 
                    AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
                    AutoGenerateEditButton="True" BackColor="White" 
                    BackImageUrl="~/Images/Shopping-Bag-Pantene.jpg" BorderColor="#CCCCCC" 
                    BorderStyle="None" BorderWidth="1px" CellPadding="4" DataKeyNames="Brand_ID" 
                    DataSourceID="SqlDataSource1" ForeColor="Black" GridLines="None" Width="924px">
                    <Columns>
                        <asp:BoundField DataField="Brand_ID" HeaderText="Brand_ID" 
                            InsertVisible="False" ReadOnly="True" SortExpression="Brand_ID" />
                        <asp:BoundField DataField="Brand_Name" HeaderText="Brand_Name" 
                            SortExpression="Brand_Name" />
                        <asp:BoundField DataField="Category_ID" HeaderText="Category_ID" 
                            SortExpression="Category_ID" />
                    </Columns>
                    <FooterStyle BackColor="#CCCC99" ForeColor="Black" />
                    <HeaderStyle BackColor="#333333" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="White" ForeColor="Black" HorizontalAlign="Right" />
                    <SelectedRowStyle BackColor="#CC3333" Font-Bold="True" ForeColor="White" />
                    <SortedAscendingCellStyle BackColor="#F7F7F7" />
                    <SortedAscendingHeaderStyle BackColor="#4B4B4B" />
                    <SortedDescendingCellStyle BackColor="#E5E5E5" />
                    <SortedDescendingHeaderStyle BackColor="#242121" />
                </asp:GridView>
                <asp:SqlDataSource ID="SqlDataSource3" runat="server" 
                    ConnectionString="<%$ ConnectionStrings:ConnectionString %>" 
                    SelectCommand="SELECT * FROM [Category_Table]"></asp:SqlDataSource>
            </td>
        </tr>
        <tr>
            <td>
                &nbsp;</td>
            <td>
                &nbsp;</td>
        </tr>
        <tr>
            <td>
                &nbsp;</td>
            <td>
                &nbsp;</td>
        </tr>
        <tr>
            <td colspan="2">
                <asp:GridView ID="GridView3" runat="server" AllowPaging="True" 
                    AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
                    AutoGenerateEditButton="True" BackColor="White" 
                    BackImageUrl="~/Images/abstract-design.jpg" BorderColor="#CCCCCC" 
                    BorderStyle="None" BorderWidth="1px" CellPadding="4" DataKeyNames="Product_ID" 
                    DataSourceID="SqlDataSource2" ForeColor="Black" GridLines="None" Width="924px">
                    <Columns>
                        <asp:BoundField DataField="Product_ID" HeaderText="Product_ID" 
                            InsertVisible="False" ReadOnly="True" SortExpression="Product_ID" />
                        <asp:TemplateField HeaderText="Product_Image" SortExpression="Product_Image">
                            <EditItemTemplate>
                                <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("Product_Image") %>'></asp:TextBox>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Image ID="Image9" runat="server" Height="100px" 
                                    ImageUrl='<%# Bind("Product_Image") %>' Width="100px" />
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:BoundField DataField="Category_ID" HeaderText="Category_ID" 
                            SortExpression="Category_ID" />
                        <asp:BoundField DataField="Brand_ID" HeaderText="Brand_ID" 
                            SortExpression="Brand_ID" />
                        <asp:BoundField DataField="Product_Name" HeaderText="Product_Name" 
                            SortExpression="Product_Name" />
                        <asp:BoundField DataField="Product_Details" HeaderText="Product_Details" 
                            SortExpression="Product_Details" />
                    </Columns>
                    <FooterStyle BackColor="#CCCC99" ForeColor="Black" />
                    <HeaderStyle BackColor="#333333" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="White" ForeColor="Black" HorizontalAlign="Right" />
                    <SelectedRowStyle BackColor="#CC3333" Font-Bold="True" ForeColor="White" />
                    <SortedAscendingCellStyle BackColor="#F7F7F7" />
                    <SortedAscendingHeaderStyle BackColor="#4B4B4B" />
                    <SortedDescendingCellStyle BackColor="#E5E5E5" />
                    <SortedDescendingHeaderStyle BackColor="#242121" />
                </asp:GridView>
                <asp:SqlDataSource ID="SqlDataSource2" runat="server" 
                    ConnectionString="<%$ ConnectionStrings:ConnectionString %>" 
                    SelectCommand="SELECT * FROM [Product_Table]"></asp:SqlDataSource>
            </td>
        </tr>
        <tr>
            <td>
                &nbsp;</td>
            <td>
                &nbsp;</td>
        </tr>
    </table>
    </asp:Content>

